apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: {{ .Release.Name }}-hpa
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployement
        name: {{ .Release.Name }}-deployment
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80