- name: Install kubelet, kubeadm, and kubectl
  yum:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present

- name: Enable and start kubelet
  systemd:
    name: kubelet
    enabled: true
    state: started

- name: Initialize Kubernetes Cluster
  command: kubeadm init
  when: ansible_hostname == "k8s-master"